# vim: sw=2

name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

permissions:
  contents: read #  to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  DEBIAN_FRONTEND: noninteractive

jobs:

  rip-and-test:
    runs-on: ubuntu-26.04
    timeout-minutes: 45
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        fetch-depth: 1
    - name: Install dependencies
      run: |
        set -x
        .github/scripts/install-deps.sh
    - name: Build RIP GCC
      run: |
        set -x
        gcc --version
        .github/scripts/build-rip.sh --with-realtime=uspace
    - name: Test1
      run: |
        scripts/rip-environment bin/rs274 -g tests/interp/g71-with-g70/g71-with-g70.ngc
    - name: Test2
      run: |
        scripts/rip-environment bin/rs274 -g tests/interp/g71-with-g70/g71-with-g70.ngc | awk '{$1=""; print}'
    - name: Verify no untracked or modified files after build
      run: |
        .github/scripts/verify-clean-repo.sh
    - name: Test
      run: |
        set -x
        scripts/rip-environment runtests -p
    - name: Verify no untracked or modified files after test
      run: |
        .github/scripts/verify-clean-repo.sh
